language: python 
python: 
- '3.7'
before_install:
- pip install pytest
- pip install coveralls
install:
- python setup.py build_ext --inplace
- pip install -r requirements.txt 
script:
- coverage run -m pytest ./tests
after_sucess:
  coveralls
