language: python 
python: 
- '3.7'
before_install:
- pip install -U pytest codecov
install:
- python setup.py build_ext --inplace
- pip install -r requirements.txt 
script:
- pytest ./tests
after_sucess:
  codecov
